### ISSUE TITLE
proj:shape for several rasters in the product

### ISSUE THREAD

**Issue by cbouzina** [stac-extensions/projection#19]
Would it be possible to provide several shapes for a product including several rasters with different shapes please ? 

For example, this is the case of Sentinel-3 SLSTR RBT and LST product types.

**Comment by m-mohr** [comment]
@cbouzina  You can provide proj:shape per asset. Is this enough or do you need to provide it on a per-band basis?

**Comment by cbouzina** [comment]
We dont plan to use the asset object for now. 

However we can provide only the shape of the raster with the best resolution, if the projection extension is not modified.

**Comment by m-mohr** [comment]
@cbouzina what is the unit that you want proj:shape to provide for if it's not per asset or per band? It sounds like your data model is flawed and just inventing a 'best resolution' will not be understood by users/tooling. Right now it's also unclear what the proposal/request is for this issue... 🤔

**Comment by m-mohr** [comment]
Seems stale, closing until further input is provided.
