### ISSUE TITLE
null EPSG codes for complex coordinate systems

### ISSUE THREAD

**Issue by hobu** [stac-extensions/projection#6]
Current version of the extension states that `proj:epsg` is **REQUIRED**. I'm indexing a bunch of elevation content that is in compound coordinate systems for which there isn't a simple EPSG code. I can definitely provide a very complex `proj:projjson` object for the item, but boiling that down to a simple EPSG code that represents the entire thing is a fools' errand. 

`null` for `proj:epsg` is allowed, but that section of the text doesn't tell the consumer what they should do if it is null.

Could that section also include something like: 

> For data with a `null` `proj:epsg` for which there is a coordinate definition, it can be provided in `proj::wkt2` OR `proj::projjson`. Clients can prefer to take either, although there may be discrepancies in how each might be interpreted.

**Comment by m-mohr** [comment]
That makes sense and I think that is indeed what was meant originally. Do you agree, @matthewhanson ?

**Comment by emmanuelmathot** [comment]
Indeed, that the initial. Typically satellite imagery data in their own acquisition reference.
