### ISSUE TITLE
IAU

### ISSUE THREAD

**Issue by J-Christophe** [stac-extensions/projection#8]
Hello,

Very nice extension. For the needs of planetology, could you add proj:iau please ?

IAU is the International Astronomical Union. This organisation provides the reference systems for solar system planets, moons and some of the asteroids/asteroids.

We have created a group at OGC (https://www.ogc.org/pressroom/pressreleases/4504)  where the aim is to extend OGC standards (https://defs.opengis.net/vocprez/object?uri=http%3A//www.opengis.net/def/auth/iau) for planetology. Currently, we had integrated the IAU code in proj (PROJ >= 8.2.0) and GDAL(https://github.com/OSGeo/gdal/pull/5287). 
ex : gdalsrsinfo IAU:2015:49910

Thanks,
Jean-Christophe

**Comment by hobu** [comment]
@J-Christophe Make a PR with this addition.
