### ISSUE TITLE
Suggestion: tweak text for `proj:transform` to warn off common pitfalls

### ISSUE THREAD

**Issue by Kirill888** [stac-extensions/projection#9]
https://github.com/stac-extensions/projection/blob/7f1d1c9db7c33dba0944972a983d74fd480d4c62/README.md?plain=1#L101-L109

Description above mentions `GetGeoTransform` and `rio info`. These two produce different formats on output, and while this extension is compatible with `rio info`, data from `GetGeoTransform` needs to be re-arranged. I think it's easy enough to assume that you can just stick output of `GetGeoTransform` into the stac document, but this is not the case.

**Comment by hobu** [comment]
Make a PR that updates the language and it is quite likely to be merged.
